# Configuração do banco de dados PostgreSQL
spring:
    datasource:
        url: jdbc:postgresql://localhost/devfood
        username: postgres
        password: postgres
        hikari:
            maximum-pool-size: 30
            minimum-idle: 20
            idle-timeout: 10000
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
        open-in-view: true
    flyway:
        locations: classpath:db/migration,classpath:db/datatest
#    jackson:
#        deserialization:
#            fail-on-unknown-properties: true
#            fail-on-ignored-properties: true
    messages:
        basename: messages
        fallback-to-system-locale: false
